export const HIDE_LAYOUT_ELEMENTS = "HIDE_LAYOUT_ELEMENTS";
export const GET_INIT_VALUES = "GET_INIT_VALUES";
export const GET_INITIAL_DATA = "GET_INITIAL_DATA";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
